### ISSUE TITLE
Assertion failure when trying to list scenarios while there are unsaved changes.

### ISSUE THREAD

**Issue by geoo89** [nstbayless/gyoa#1]
alert: un[s]aved changes.

Enter command. Press [h] for help.

> i
> gyoa: ../src/backend/ops/Operation.cpp:233: void gyoa::ops::Operation::reload(): Assertion `!savePending()' failed.
> Aborted

**Comment by nstbayless** [comment]
Fixed.

Cause: to list all rooms with title information, all rooms must be loaded in memory, so the Operation::loadAll() method is invoked. This method, however, reloads even rooms that have been edited. Edited rooms should not be reloaded until they have been saved, this causes the assertion failure.

Fix: added a new method, Operation::loadAllUnloaded(), which only loads any rooms that have not yet been loaded.
